### ISSUE TITLE
Update Panel to 1.11

### ISSUE THREAD

**Issue by MikeEchoVoid** [Gethec/Pterodactyl-Panel#2]
Hi, 
thank you for your great work. I'm using your docker image.
Is there a way to update the panel ? I'm running 1.10.3

Thanks for your help.

**Comment by Gethec** [comment]
Hello!  I'm glad you're enjoying my little side project.  Regarding updates, if you're running either the "latest" or the "s6-v3" tags, you should be able to just pull the latest container image and be on the most current versions.  There is a build issue with "s6-v2" that I haven't had a chance to troubleshoot, but since it is essentially the same as the "latest" tag at the moment, you shouldn't need it.

All of that said, I will be shifting the "latest" tag over to "s6-v3" when I have a chance, and encourage you to go ahead and adapt that container version since S6-Overlay is no longer maintaining the V2 release of their application.  There should be no functional difference for you - just swap the tag and restart.  I mostly delineated which is which for possible issues and clarity.

**Comment by MikeEchoVoid** [comment]
Thank you for your answer. 
Wil the database of the panel be updated automatically ?

**Comment by Gethec** [comment]
It will.  Cache clears and and a database check runs on every container launch - for non-upgrade launches it does nothing, but it allows the container to automatically handle upgrades when a new version of the Panel is run.

**Comment by MikeEchoVoid** [comment]
Thanks. It's wonderfull, very simple to update :)
